FROM debian:bullseye-slim AS builder

ENV USER=rdns
ENV UID=10001

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

FROM gcr.io/distroless/cc

ARG TARGETPLATFORM

EXPOSE 53/tcp
EXPOSE 53/udp

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

WORKDIR /rdns
COPY ./${TARGETPLATFORM}/rdns ./rdns

USER rdns:rdns

ENTRYPOINT ["/rdns/rdns"]
